name: C/C++ CI

on: push

env:
  BUILD_TYPE: Debug

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
#     - name: configure
#       run: ./configure
#     - name: make
#       run: make
#     - name: make check
#       run: make check
#     - name: make distcheck
#       run: make distcheck
    
    - name: Install dependencies
      run: |
        sudo apt-get install valgrind +universal
        echo "Valgrind installed"
        chmod a+x ./todoapp
    
    - name: Test 1 Full
      run: |
        valgrind --error-exitcode=1 --leak-check=full ./todoapp
